"""
CATERYA Export Engine — PDF/HTML/Markdown
Author : Ary HH <cateryatech@proton.me>

PDF root-cause: ReportLab built-in fonts only support Latin-1.
Emoji chars cause "An error was encountered while processing the file."
Fix: replace all emoji with ASCII before PDF rendering.
"""
from __future__ import annotations
import io, re
from datetime import datetime
from typing import Any, Dict

_EMOJI_MAP = {
    "\U0001f50d":"[Research]","\U0001f9e0":"[Analysis]","\u270d\ufe0f":"[Writer]",
    "\U0001f4e3":"[Marketing]","\U0001f4bc":"[Sales]","\U0001f4b0":"[Finance]",
    "\U0001f3d7\ufe0f":"[Architect]","\u2699\ufe0f":"[Backend]","\U0001f3a8":"[Frontend]",
    "\u2696\ufe0f":"[Ethics]","\u2705":"[PASS]","\u274c":"[FAIL]","\u26a0\ufe0f":"[WARN]",
    "\U0001f4c4":"[Doc]","\U0001f4ca":"[Chart]","\U0001f52c":"[Eval]",
    "\u2b21":"[CATERYA]","\u2192":"->","\u00b7":".","\u2026":"...",
    "\u2019":"'","\u2018":"'","\u201c":'"',"\u201d":'"',"\u2013":"-","\u2014":"--",
}

def _pdf_safe(text: str) -> str:
    if not text: return ""
    for emoji, rep in _EMOJI_MAP.items():
        text = text.replace(emoji, rep)
    return text.encode("latin-1", errors="ignore").decode("latin-1")

def _now() -> str:
    return datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

def _safe(t):  return (t or "").strip()
def _shtml(t): return re.sub(r"<[^>]+>", "", t or "")


def to_markdown(result: Dict[str, Any], mode: str = "analyse", query: str = "") -> str:
    cos = result.get("cos_result", {})
    if not isinstance(cos, dict): cos = {}
    cs  = cos.get("cos", 0.0)
    psd = "PASS" if cs >= 0.7 else "FAIL"
    lines = [
        "# CATERYA Enterprise Report","",
        f"**Query:** {query}",
        f"**Mode:** {mode.upper()}",
        f"**Generated:** {_now()}",
        f"**COS Score:** `{cs:.4f}` -- {psd}","","---","",
    ]
    if mode == "build":
        secs = [
            ("## Architecture Design", result.get("architect_output","")),
            ("## Backend Code",        result.get("backend_code","")),
            ("## Frontend Code",       result.get("frontend_code","")),
        ]
    else:
        secs = [
            ("## Research",             result.get("research_output","")),
            ("## Analysis",             result.get("analysis_output","")),
            ("## Synthesis",            result.get("final_output","")),
            ("## Marketing Strategy",   result.get("marketing_output","")),
            ("## Sales Strategy",       result.get("sales_output","")),
            ("## Financial Projection", result.get("finance_output","")),
        ]
    for h,c in secs:
        if c and c.strip(): lines += [h,"",_safe(c),"","---",""]
    pillars = cos.get("pillars",[])
    if pillars:
        lines += ["## Ethical Evaluation","",f"**COS:** {cs:.4f} -- {psd}","",
                  "| Pillar | Score | Status |","|---|---|---|"]
        for p in pillars:
            s=p.get("score",0); st="PASS" if s>=0.7 else ("WARN" if s>=0.5 else "FAIL")
            lines.append(f"| {p.get('name','').replace('_',' ').title()} | {s:.3f} | {st} |")
    lines.append("\n*Generated by CATERYA Enterprise*")
    return "\n".join(lines)


def to_html(result: Dict[str, Any], mode: str = "analyse", query: str = "") -> str:
    try:
        import markdown as md_lib
        def md2h(t): return md_lib.markdown(t or "", extensions=["fenced_code","tables"])
    except ImportError:
        def md2h(t):
            s=(t or "").replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
            return "<br>".join(s.splitlines())
    cos=result.get("cos_result",{})
    if not isinstance(cos,dict): cos={}
    cs=cos.get("cos",0.0); psd="PASS" if cs>=0.7 else "FAIL"
    bc="#00c99a" if cs>=0.7 else "#ff5555"
    if mode=="build":
        secs=[("Architecture Design",result.get("architect_output","")),
              ("Backend Code",result.get("backend_code","")),
              ("Frontend Code",result.get("frontend_code",""))]
    else:
        secs=[("Research",result.get("research_output","")),
              ("Analysis",result.get("analysis_output","")),
              ("Final Synthesis",result.get("final_output","")),
              ("Marketing Strategy",result.get("marketing_output","")),
              ("Sales Strategy",result.get("sales_output","")),
              ("Financial Projection",result.get("finance_output",""))]
    sec_html=""
    for title,c in secs:
        if c and c.strip():
            sec_html+=f"<section class='section'><h2>{title}</h2><div class='content'>{md2h(c)}</div></section>"
    pil_rows=""
    for p in cos.get("pillars",[]):
        s=p.get("score",0); clr="#00c99a" if s>=0.7 else ("#ffaa00" if s>=0.5 else "#ff5555")
        pct=int(s*100)
        pil_rows+=f"<tr><td>{p.get('name','').replace('_',' ').title()}</td><td><div style='background:#1a1a30;border-radius:4px;height:8px;width:200px'><div style='background:{clr};height:8px;width:{pct}%;border-radius:4px'></div></div></td><td style='color:{clr};font-weight:700'>{s:.3f}</td></tr>"
    cos_sec=""
    if pil_rows:
        cos_sec=f"<section class='section'><h2>Ethical Evaluation</h2><p style='font-family:Space Mono,monospace;color:{bc};font-size:18px;font-weight:700'>COS {cs:.4f} -- {psd}</p><table>{pil_rows}</table></section>"
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>CATERYA Report</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syne:wght@400;700;800&display=swap');
*{{box-sizing:border-box;margin:0;padding:0}}
body{{background:#07070f;color:#e8e8f8;font-family:Syne,sans-serif;padding:40px 20px}}
.wrapper{{max-width:900px;margin:0 auto}}
header{{border-bottom:2px solid #2a2a4a;padding-bottom:24px;margin-bottom:32px}}
.logo{{font-size:28px;font-weight:800;background:linear-gradient(135deg,#6c63ff,#00d4ff);-webkit-background-clip:text;-webkit-text-fill-color:transparent}}
.meta{{font-family:Space Mono,monospace;font-size:12px;color:#5a5a8a;margin-top:8px}}
.cos-badge{{display:inline-block;padding:6px 16px;border-radius:20px;font-weight:700;font-family:Space Mono,monospace;font-size:14px;margin-top:12px;background:{bc}22;color:{bc};border:1px solid {bc}55}}
.section{{background:#0f0f22;border:1px solid #2a2a4a;border-radius:12px;padding:28px;margin-bottom:24px}}
.section h2{{font-size:18px;font-weight:800;color:#e8e8f8;margin-bottom:16px;border-bottom:1px solid #2a2a4a;padding-bottom:10px}}
.content{{color:#c8c8e0;line-height:1.8;font-size:14px}}
.content h1,.content h2,.content h3{{color:#e8e8f8;margin:16px 0 8px}}
.content p{{margin:8px 0}}
.content pre{{background:#080818;border:1px solid #2a2a4a;border-radius:6px;padding:16px;overflow-x:auto;font-family:Space Mono,monospace;font-size:12px;line-height:1.6;margin:12px 0}}
.content code{{font-family:Space Mono,monospace;font-size:12px;background:#0c0c1e;padding:2px 6px;border-radius:4px}}
.content table,.content th,.content td{{border:1px solid #2a2a4a;border-collapse:collapse;padding:8px 12px}}
.content th{{background:#141428;color:#a0a0d0}}
table{{width:100%;border-collapse:collapse;margin-top:12px}}
td{{padding:10px 12px;border-bottom:1px solid #1a1a30;color:#c8c8e0}}
footer{{text-align:center;margin-top:48px;font-family:Space Mono,monospace;font-size:11px;color:#2a2a4a}}
</style></head><body><div class="wrapper">
<header><div class="logo">CATERYA Enterprise</div>
<div class="meta">Query: {_shtml(query[:120])}<br>Mode: {mode.upper()} &middot; Generated: {_now()}</div>
<div class="cos-badge">COS {cs:.4f} &mdash; {psd}</div></header>
{sec_html}{cos_sec}
<footer>Generated by CATERYA Enterprise &middot; cateryatech@proton.me &middot; Apache 2.0</footer>
</div></body></html>"""


def to_pdf(result: Dict[str, Any], mode: str = "analyse", query: str = "") -> bytes:
    """
    Generate PDF. All text passes through _pdf_safe() to replace emoji/Unicode
    before hitting ReportLab's Latin-1 fonts.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer,
            HRFlowable, Table, TableStyle, Preformatted
        )
        from reportlab.lib.enums import TA_CENTER

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4,
            leftMargin=2.2*cm, rightMargin=2.2*cm,
            topMargin=2.2*cm, bottomMargin=2.2*cm,
            title=_pdf_safe(f"CATERYA Report - {query[:60]}"),
            author="CATERYA Enterprise")
        styles = getSampleStyleSheet()

        CA=colors.HexColor("#6c63ff"); CP=colors.HexColor("#00c99a")
        CF=colors.HexColor("#ff5555"); CW=colors.HexColor("#ffaa00")
        CD=colors.HexColor("#1a1a30"); CB=colors.HexColor("#0f0f22")
        CG=colors.HexColor("#8080b0"); CT=colors.HexColor("#c8c8e0")
        CWH=colors.HexColor("#e8e8f8")

        def ps(name,**kw):
            base=kw.pop("parent",styles["Normal"])
            return ParagraphStyle(name,parent=base,**kw)

        ST=ps("T",fontName="Helvetica-Bold",fontSize=20,textColor=CA,spaceAfter=4,leading=26)
        SH=ps("H",fontName="Helvetica-Bold",fontSize=13,textColor=CWH,spaceBefore=16,spaceAfter=5,leading=18)
        SH2=ps("H2",fontName="Helvetica-Bold",fontSize=10,textColor=CG,spaceBefore=8,spaceAfter=3)
        SB=ps("B",fontName="Helvetica",fontSize=10,textColor=CT,leading=16,spaceAfter=4)
        SM=ps("M",fontName="Courier",fontSize=9,textColor=CG)
        SC=ps("C",fontName="Courier",fontSize=8,textColor=colors.HexColor("#a0d0ff"),
              backColor=colors.HexColor("#08080f"),leading=11,leftIndent=10,rightIndent=10,
              spaceBefore=2,spaceAfter=5)
        SF=ps("F",fontName="Courier",fontSize=8,textColor=CG,alignment=TA_CENTER)

        cos=result.get("cos_result",{})
        if not isinstance(cos,dict): cos={}
        cs=cos.get("cos",0.0); psd="PASS" if cs>=0.7 else "FAIL"
        cc=CP if cs>=0.7 else CF

        story=[]
        story.append(Paragraph("CATERYA Enterprise",ST))
        story.append(Paragraph("AI-Powered Business Intelligence",SM))
        story.append(Spacer(1,8))

        mdata=[["Query",_pdf_safe(query[:120])],["Mode",mode.upper()],["Generated",_now()]]
        mt=Table(mdata,colWidths=[3*cm,14*cm])
        mt.setStyle(TableStyle([
            ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"),("FONTNAME",(1,0),(1,-1),"Helvetica"),
            ("FONTSIZE",(0,0),(-1,-1),9),("TEXTCOLOR",(0,0),(0,-1),CG),("TEXTCOLOR",(1,0),(1,-1),CT),
            ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
            ("LINEBELOW",(0,-1),(-1,-1),0.5,CD),
        ]))
        story.append(mt)
        story.append(Spacer(1,10))

        ctdata=[["COS Score",f"{cs:.4f}",psd]]
        ct=Table(ctdata,colWidths=[4*cm,3.5*cm,3.5*cm])
        ct.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,-1),CB),("FONTNAME",(0,0),(-1,-1),"Courier-Bold"),
            ("FONTSIZE",(0,0),(-1,-1),11),("TEXTCOLOR",(0,0),(0,0),CG),
            ("TEXTCOLOR",(1,0),(1,0),CA),("TEXTCOLOR",(2,0),(2,0),cc),
            ("BOX",(0,0),(-1,-1),1.5,CA),
            ("TOPPADDING",(0,0),(-1,-1),10),("BOTTOMPADDING",(0,0),(-1,-1),10),
            ("LEFTPADDING",(0,0),(-1,-1),14),
        ]))
        story.append(ct)
        story.append(Spacer(1,14))
        story.append(HRFlowable(width="100%",thickness=1,color=CD))
        story.append(Spacer(1,6))

        if mode=="build":
            secs=[("Architecture Design",result.get("architect_output","")),
                  ("Backend Code",result.get("backend_code","")),
                  ("Frontend Code",result.get("frontend_code",""))]
        else:
            secs=[("Research",result.get("research_output","")),
                  ("Analysis",result.get("analysis_output","")),
                  ("Final Synthesis",result.get("final_output","")),
                  ("Marketing Strategy",result.get("marketing_output","")),
                  ("Sales Strategy",result.get("sales_output","")),
                  ("Financial Projection",result.get("finance_output",""))]

        for heading,content in secs:
            if not content or not content.strip(): continue
            story.append(Paragraph(_pdf_safe(heading),SH))
            in_code=False; code_buf=[]; para_buf=[]
            for raw in content.splitlines():
                line=_pdf_safe(raw); stripped=line.strip()
                if stripped.startswith("```"):
                    if in_code:
                        ct2="\n".join(code_buf)
                        if ct2.strip(): story.append(Preformatted(ct2,SC))
                        code_buf=[]; in_code=False
                    else:
                        if para_buf:
                            story.append(Paragraph(" ".join(para_buf),SB)); para_buf=[]
                        in_code=True
                    continue
                if in_code: code_buf.append(line); continue
                if stripped.startswith("### "):
                    if para_buf: story.append(Paragraph(" ".join(para_buf),SB)); para_buf=[]
                    story.append(Paragraph(stripped[4:],SH2))
                elif stripped.startswith("## "):
                    if para_buf: story.append(Paragraph(" ".join(para_buf),SB)); para_buf=[]
                    story.append(Paragraph(stripped[3:],SH))
                elif stripped in ("---","___"):
                    if para_buf: story.append(Paragraph(" ".join(para_buf),SB)); para_buf=[]
                    story.append(HRFlowable(width="100%",thickness=0.5,color=CD))
                elif stripped=="":
                    if para_buf: story.append(Paragraph(" ".join(para_buf),SB)); para_buf=[]
                else:
                    xml=stripped.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
                    para_buf.append(xml)
            if code_buf: story.append(Preformatted("\n".join(code_buf),SC))
            if para_buf: story.append(Paragraph(" ".join(para_buf),SB))
            story.append(Spacer(1,6))

        pillars=cos.get("pillars",[])
        if pillars:
            story.append(HRFlowable(width="100%",thickness=1,color=CD))
            story.append(Spacer(1,6))
            story.append(Paragraph("Ethical Evaluation (COS)",SH))
            pdata=[["Pillar","Score","Status"]]
            for p in pillars:
                s=p.get("score",0); st="PASS" if s>=0.7 else ("WARN" if s>=0.5 else "FAIL")
                pdata.append([p.get("name","").replace("_"," ").title(),f"{s:.3f}",st])
            pt=Table(pdata,colWidths=[6*cm,3*cm,3*cm])
            pt.setStyle(TableStyle([
                ("BACKGROUND",(0,0),(-1,0),CD),("TEXTCOLOR",(0,0),(-1,0),CG),
                ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTNAME",(0,1),(-1,-1),"Courier"),
                ("FONTSIZE",(0,0),(-1,-1),9),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[CB,colors.HexColor("#101022")]),
                ("BOX",(0,0),(-1,-1),1,CD),("GRID",(0,0),(-1,-1),0.5,CD),
                ("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7),
                ("LEFTPADDING",(0,0),(-1,-1),10),
            ]))
            for ri,p in enumerate(pillars,1):
                s=p.get("score",0); rc=CP if s>=0.7 else (CW if s>=0.5 else CF)
                pt.setStyle(TableStyle([("TEXTCOLOR",(1,ri),(2,ri),rc)]))
            story.append(pt)

        story.append(Spacer(1,28))
        story.append(Paragraph(
            "Generated by CATERYA Enterprise  |  cateryatech@proton.me  |  Apache 2.0",SF))

        doc.build(story)
        return buf.getvalue()

    except Exception as exc:
        import traceback as _tb
        fallback=f"PDF Error: {exc}\n\n{_tb.format_exc()}\n\n"+to_markdown(result,mode,query)
        return fallback.encode("utf-8")
